print(1+2)
print(2-1)
print(2*3)
print(2/4)
print(2**3)
print(2//3)
print(2%4)
print("Familia------------------>")
print("Miguel")
print("Andrés")
print("Rebeca") 
print("Carmen")
print("país--------------------->")
print("españa")
print("estoy disfrutando de 30 dias de python")
print(type(10))
print(type(9.8))
print(type(3.14))
print(type(4 + 4j))
print(type(["Asbeneh","Python","Finland"]))
print(type({"Miguel"}))
print(type("Carmen, andres y rebeca"))
print(type("ESPAÑA"))

