print(1+2)
print(2-1)
print(2*3)
print(2/4)
print(2**3)
print(2//3)
print(2%4)
print("Familia------------------>")
print("Miguel")
print("Andrés")
print("Rebeca")
print("Carmen")
print("país--------------------->")
print("ESPAÑA")
print("im enjoying 30 days of python")
print("data types:")
print("integer is 3, float is 5.7, complex is 4-4j")


